# Generated by Django 2.0.2 on 2018-02-14 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='waga [g]')),
                ('fineness', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000)], verbose_name='próba [/1000]')),
                ('country', models.CharField(max_length=100, verbose_name='państwo')),
                ('face_value', models.CharField(max_length=100, verbose_name='nominał')),
                ('mint_years', models.CharField(max_length=100, verbose_name='lata wydania')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='opis')),
            ],
            options={
                'verbose_name': 'Moneta',
                'verbose_name_plural': 'Monety',
            },
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('stooq_symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='nazwa')),
                ('short', models.CharField(max_length=10, verbose_name='skrót')),
            ],
            options={
                'verbose_name': 'Metal',
                'verbose_name_plural': 'Metale',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='czas')),
                ('value', models.FloatField(verbose_name='wartość')),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bullion.Metal', verbose_name='metal')),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'Ceny',
            },
        ),
        migrations.AddField(
            model_name='coin',
            name='metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bullion.Metal'),
        ),
    ]
