# Generated by Django 2.0.2 on 2018-02-14 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='value',
        ),
        migrations.AddField(
            model_name='price',
            name='value_per_oz',
            field=models.FloatField(default=0, verbose_name='wartość 1 oz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bullion.Metal', verbose_name='metal'),
        ),
    ]
