# Generated by Django 2.0.2 on 2018-02-14 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bullion', '0002_auto_20180214_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='czas'),
        ),
    ]
