# Generated by Django 2.0.2 on 2018-02-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullion', '0003_auto_20180214_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='czas'),
        ),
    ]
