# Generated by Django 2.0.2 on 2018-02-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullion', '0004_auto_20180214_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='mint_years',
            field=models.CharField(max_length=100, verbose_name='lata bicia'),
        ),
    ]
